# mpc
receding: 5
step_time: 0.3
ref_speed: 0.5
device: 'cpu'
time_print: False
collision_threshold: 0.001

# robot
robot:
  kinematics: 'diff'
  max_speed: [1, 1.57]
  max_acce: [1, 1.57]
  length: 0.63
  width: 0.59

# initial path
ipath:
  interval: 0.09
  waypoints: [[0, 0, 0], [3, 0, 0]]
  curve_style: 'line'   # 'dubins' or reeds or line
  min_radius: 0.0
  loop: True
  arrive_threshold: 1.0
  close_threshold: 0.1
  arrive_index_threshold: 3
  
# proximal alternating minimization network
pan:
  iter_num: 4
  dune_max_num: 100
  nrmp_max_num: 50
  dune_checkpoint: None
  iter_threshold: 0.1

# adjust parameters
adjust:
  q_s: 0.2
  p_u: 1.0
  eta: 10.0
  ro_obs: 500
  d_max: 0.2
  d_min: 0.01
